namespace SafeIR.PluginAnalyzer;

using System.Text;

internal static class SafeIrPackageSourceEmitter
{
    public static GeneratedPluginPackage Emit(PluginKernelModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(model.Namespace)) {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(model.PackageName).AppendLine();
        builder.AppendLine("{");
        EmitBody(builder, model);
        builder.AppendLine("}");
        return new GeneratedPluginPackage(HintName(model), builder.ToString());
    }

    private static string HintName(PluginKernelModel model)
        => string.IsNullOrWhiteSpace(model.Namespace)
            ? model.PackageName + ".g.cs"
            : HintNamePart(model.Namespace) + "." + model.PackageName + ".g.cs";

    private static string HintNamePart(string value)
        => value.Replace(SafeIrGenerationNames.CSharpIdentifiers.EscapePrefix, string.Empty);

    private static void EmitBody(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static readonly global::SafeIR.SourceSpan Span = new(")
            .Append(SafeIrGenerationNames.GeneratedSpanLine)
            .Append(", ")
            .Append(SafeIrGenerationNames.GeneratedSpanColumn)
            .AppendLine(");");
        builder.AppendLine();
        builder.AppendLine("    public static global::SafeIR.Plugins.PluginPackage Create()");
        builder.AppendLine("    {");
        EmitSettings(builder, model);
        builder.AppendLine("        var manifest = new global::SafeIR.Plugins.PluginManifest(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine(
            $"            {LiteralReader.StringLiteral(SafeIrGenerationNames.Contracts.EventKernel(model.EventName))},");
        builder.AppendLine("            global::SafeIR.ExecutionMode.Auto,");
        EmitEffects(builder, model.ManifestEffects);
        builder.AppendLine("            settings,");
        builder.AppendLine($"            [new global::SafeIR.Plugins.HookSubscriptionManifest({LiteralReader.StringLiteral(model.EventName)}, {LiteralReader.StringLiteral(model.KernelName)})]);");
        builder.AppendLine("        return global::SafeIR.Plugins.PluginPackage.Create(manifest, CreateModule(settings));");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitModule(builder, model);
        EmitFunctions(builder, model);
        EmitHelpers(builder, model);
    }

    private static void EmitSettings(StringBuilder builder, PluginKernelModel model)
    {
        if (model.LiveSettings.Count == 0) {
            builder.AppendLine("        var settings = global::System.Array.Empty<global::SafeIR.Plugins.LiveSettingDefinition>();");
            return;
        }

        builder.AppendLine("        var settings = new global::SafeIR.Plugins.LiveSettingDefinition[] {");
        foreach (var setting in model.LiveSettings) {
            builder.Append("            new global::SafeIR.Plugins.LiveSettingDefinition(");
            builder.Append(LiteralReader.StringLiteral(setting.Name)).Append(", ");
            builder.Append(LiteralReader.StringLiteral(setting.Type)).Append(", ");
            builder.Append(setting.DefaultValue);
            if (setting.Min is not null || setting.Max is not null) {
                builder.Append(", ")
                    .Append(setting.Min ?? SafeIrGenerationNames.CSharpLiterals.Null)
                    .Append(", ")
                    .Append(setting.Max ?? SafeIrGenerationNames.CSharpLiterals.Null);
            }

            builder.AppendLine("),");
        }

        builder.AppendLine("        };");
    }

    private static void EmitEffects(StringBuilder builder, EquatableArray<string> effects)
    {
        builder.Append("            [");
        for (var i = 0; i < effects.Count; i++) {
            if (i > 0) {
                builder.Append(", ");
            }

            builder.Append(LiteralReader.StringLiteral(effects[i]));
        }

        builder.AppendLine("],");
    }

    private static void EmitModule(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("    private static global::SafeIR.SandboxModule CreateModule(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("    {");
        builder.AppendLine("        var parameters = Parameters(settings);");
        builder.AppendLine("        return new global::SafeIR.SandboxModule(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine("            global::SafeIR.SemVersion.One,");
        builder.AppendLine("            global::SafeIR.SemVersion.One,");
        builder.AppendLine(
            $"            [new global::SafeIR.CapabilityRequest(global::SafeIR.Plugins.PluginMessageBindings.CapabilityId, {LiteralReader.StringLiteral(SafeIrGenerationNames.Capabilities.MessageWriteReason)})],");
        builder.Append("            [")
            .Append(SafeIrGenerationNames.Entrypoints.ShouldHandle)
            .Append("(parameters), ")
            .Append(SafeIrGenerationNames.Entrypoints.Handle)
            .AppendLine("(parameters)],");
        builder.AppendLine($"            new global::System.Collections.Generic.Dictionary<string, string> {{ [{LiteralReader.StringLiteral(SafeIrGenerationNames.ModuleMetadata.PluginId)}] = {LiteralReader.StringLiteral(model.PluginId)}, [{LiteralReader.StringLiteral(SafeIrGenerationNames.ModuleMetadata.Kernel)}] = {LiteralReader.StringLiteral(model.KernelName)} }});");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitFunctions(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static global::SafeIR.SandboxFunction ")
            .Append(SafeIrGenerationNames.Entrypoints.ShouldHandle)
            .AppendLine("(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Parameter> parameters)");
        builder.AppendLine("        => new(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(SafeIrGenerationNames.Entrypoints.ShouldHandle)}, true, parameters, global::SafeIR.SandboxType.Bool,");
        builder.AppendLine($"            {model.ShouldHandle.Source});");
        builder.AppendLine();
        builder.Append("    private static global::SafeIR.SandboxFunction ")
            .Append(SafeIrGenerationNames.Entrypoints.Handle)
            .AppendLine("(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Parameter> parameters)");
        builder.AppendLine("        => new(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(SafeIrGenerationNames.Entrypoints.Handle)}, true, parameters, global::SafeIR.SandboxType.Unit,");
        builder.AppendLine($"            [new global::SafeIR.ReturnStatement({HandleExpression(model.Handle)}, Span)]);");
        builder.AppendLine();
    }

    private static void EmitHelpers(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Parameter> Parameters(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("    {");
        if (model.EventProperties.Count == 0) {
            builder.AppendLine("        if (settings.Count == 0) {");
            builder.AppendLine("            return global::System.Array.Empty<global::SafeIR.Parameter>();");
            builder.AppendLine("        }");
        }

        builder.Append("        var parameters = new global::SafeIR.Parameter[settings.Count + ")
            .Append(model.EventProperties.Count)
            .AppendLine("];");
        var parameterIndex = 0;
        foreach (var property in model.EventProperties) {
            builder.Append("        parameters[")
                .Append(parameterIndex)
                .Append("] = new global::SafeIR.Parameter(");
            builder.Append(LiteralReader.StringLiteral(SafeIrExpressionModelFactory.EventVariable(property.Name)));
            builder.Append(", TypeOf(").Append(LiteralReader.StringLiteral(property.Type)).AppendLine("));");
            parameterIndex++;
        }

        builder.AppendLine("        for (var i = 0; i < settings.Count; i++) {");
        builder.AppendLine("            var setting = settings[i];");
        builder.Append("            parameters[i + ")
            .Append(model.EventProperties.Count)
            .AppendLine("] = new global::SafeIR.Parameter(setting.Name, TypeOf(setting.Type));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return parameters;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    private static global::SafeIR.SandboxType TypeOf(")
            .Append(Parameter(SafeIrGenerationNames.CSharpTypes.String, "type"))
            .AppendLine(") => type switch {");
        builder.AppendLine($"        {LiteralReader.StringLiteral(SafeIrGenerationNames.ManifestTypes.Bool)} => global::SafeIR.SandboxType.Bool,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(SafeIrGenerationNames.ManifestTypes.Int)} => global::SafeIR.SandboxType.I32,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(SafeIrGenerationNames.ManifestTypes.Long)} => global::SafeIR.SandboxType.I64,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(SafeIrGenerationNames.ManifestTypes.Double)} => global::SafeIR.SandboxType.F64,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(SafeIrGenerationNames.ManifestTypes.String)} => global::SafeIR.SandboxType.String,");
        builder.AppendLine("        _ => throw new global::System.InvalidOperationException($\"Unsupported generated setting type '{type}'.\")");
        builder.AppendLine("    };");
        builder.AppendLine();
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.Var,
            Parameter(SafeIrGenerationNames.CSharpTypes.String, "name"),
            "new global::SafeIR.VariableExpression(name, Span)");
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.Str,
            Parameter(SafeIrGenerationNames.CSharpTypes.String, "value"),
            "new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromString(value), Span)");
        EmitStringConcatHelper(builder);
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.I32,
            Parameter(SafeIrGenerationNames.CSharpTypes.Int, "value"),
            "new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromInt32(value), Span)");
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.I64,
            Parameter(SafeIrGenerationNames.CSharpTypes.Long, "value"),
            "new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromInt64(value), Span)");
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.F64,
            Parameter(SafeIrGenerationNames.CSharpTypes.Double, "value"),
            "new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromDouble(value), Span)");
        EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.Bool,
            Parameter(SafeIrGenerationNames.CSharpTypes.Bool, "value"),
            "new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromBool(value), Span)");
        EmitUnaryHelper(builder, SafeIrGenerationNames.Helpers.Not, SafeIrGenerationNames.Operators.LogicalNot);
        EmitUnaryHelper(builder, SafeIrGenerationNames.Helpers.Neg, SafeIrGenerationNames.Operators.Minus);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Eq, SafeIrGenerationNames.Operators.EqualTo);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Ne, SafeIrGenerationNames.Operators.NotEqualTo);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Ge, SafeIrGenerationNames.Operators.GreaterThanOrEqual);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Gt, SafeIrGenerationNames.Operators.GreaterThan);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Le, SafeIrGenerationNames.Operators.LessThanOrEqual);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Lt, SafeIrGenerationNames.Operators.LessThan);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.And, SafeIrGenerationNames.Operators.LogicalAnd);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Or, SafeIrGenerationNames.Operators.LogicalOr);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Add, SafeIrGenerationNames.Operators.Add);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Sub, SafeIrGenerationNames.Operators.Minus);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Mul, SafeIrGenerationNames.Operators.Multiply);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Div, SafeIrGenerationNames.Operators.Divide);
        EmitBinaryHelper(builder, SafeIrGenerationNames.Helpers.Mod, SafeIrGenerationNames.Operators.Modulo);
    }

    private static void EmitHelper(StringBuilder builder, string name, string parameters, string expression)
        => builder.Append("    private static global::SafeIR.Expression ")
            .Append(name)
            .Append('(')
            .Append(parameters)
            .Append(") => ")
            .Append(expression)
            .AppendLine(";");

    private static void EmitStringConcatHelper(StringBuilder builder)
        => EmitHelper(
            builder,
            SafeIrGenerationNames.Helpers.ConcatString,
            "global::SafeIR.Expression left, global::SafeIR.Expression right",
            "new global::SafeIR.CallExpression(" +
            LiteralReader.StringLiteral(SafeIrGenerationNames.BindingIds.StringConcatBudgeted) +
            ", [left, right], null, Span)");

    private static string Parameter(string type, string name) => type + " " + name;

    private static void EmitUnaryHelper(StringBuilder builder, string name, string op)
        => EmitHelper(
            builder,
            name,
            "global::SafeIR.Expression operand",
            $"new global::SafeIR.UnaryExpression({LiteralReader.StringLiteral(op)}, operand, Span)");

    private static void EmitBinaryHelper(StringBuilder builder, string name, string op)
        => EmitHelper(
            builder,
            name,
            "global::SafeIR.Expression left, global::SafeIR.Expression right",
            $"new global::SafeIR.BinaryExpression(left, {LiteralReader.StringLiteral(op)}, right, Span)");

    private static string HandleExpression(SafeIrHandleModel handle)
        => $"new global::SafeIR.CallExpression(global::SafeIR.Plugins.PluginMessageBindings.SendBindingId, [{handle.Target.Source}, {handle.Message.Source}], null, Span)";
}
