namespace AgentQueue;

internal sealed record AgentArea(string Name, string Prefix, string QueueFile, string DisplayName);

internal static class AgentQueueCatalog
{
    public const string QueueGeneratedWarning =
        "<!-- GENERATED BY agentq render. DO NOT EDIT BY HAND. Source of truth: docs/agent-loop/findings/*.md -->";

    public static readonly AgentArea[] Areas =
    [
        new("completeness", "CMP", "completeness.md", "Completeness"),
        new("correctness", "COR", "correctness.md", "Correctness"),
        new("perf_alloc", "PAL", "perf-alloc.md", "Perf Alloc"),
        new("perf_algorithm", "ALG", "perf-algorithm.md", "Perf Algorithm"),
        new("api_coherence", "API", "api-coherence.md", "API Coherence"),
        new("test_coverage", "TST", "test-coverage.md", "Test Coverage")
    ];

    public static readonly string[] Priorities = ["critical", "high", "medium", "low", "idea"];

    public static readonly string[] Statuses =
    [
        "open",
        "claimed",
        "fixed_pending_verification",
        "verified",
        "rejected",
        "duplicate",
        "obsolete"
    ];

    public static readonly string[] MetadataKeys =
    [
        "id",
        "area",
        "status",
        "priority",
        "title",
        "dedup_key",
        "created_at",
        "created_by",
        "created_commit",
        "updated_at",
        "claimed_by",
        "claimed_at",
        "claim_branch",
        "fixed_by",
        "fixed_at",
        "fixed_commit",
        "verified_by",
        "verified_at",
        "verified_commit",
        "duplicate_of"
    ];

    public static AgentArea RequireArea(string value)
    {
        AgentArea? area = Areas.FirstOrDefault(candidate =>
            string.Equals(candidate.Name, value, StringComparison.OrdinalIgnoreCase));

        return area ?? throw new AgentQueueException(
            $"Unknown area '{value}'. Valid areas: {string.Join(", ", Areas.Select(area => area.Name))}.",
            ExitCodes.UserError);
    }

    public static bool IsPriority(string value) =>
        Priorities.Contains(value, StringComparer.Ordinal);

    public static bool IsStatus(string value) =>
        Statuses.Contains(value, StringComparer.Ordinal);

    public static bool IsFinalStatus(string status) =>
        status is "verified" or "rejected" or "duplicate" or "obsolete";

    public static int PriorityRank(string value) =>
        Array.FindIndex(Priorities, priority => priority == value) is var index && index >= 0 ? index : int.MaxValue;

    public static int StatusRank(string value) =>
        Array.FindIndex(Statuses, status => status == value) is var index && index >= 0 ? index : int.MaxValue;

    public static bool CanTransition(string current, string next, bool force)
    {
        if (current == next)
        {
            return true;
        }

        if (IsFinalStatus(current))
        {
            return force && next == "open";
        }

        return current switch
        {
            "open" => next is "claimed" or "rejected" or "duplicate" or "obsolete",
            "claimed" => next is "open" or "fixed_pending_verification" or "rejected" or "duplicate" or "obsolete",
            "fixed_pending_verification" => next is "verified" or "open" or "rejected" or "duplicate" or "obsolete",
            _ => false
        };
    }
}
