param(
    [int] $WarnAt = 300,
    [int] $FailAt = 350,
    [int] $MaxFilesPerFolder = 15,
    [int] $MaxFilesInProjectFolder = 5
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$justificationPath = Join-Path $root ".config/code-enforcer/justifications.json"
$violations = [System.Collections.Generic.List[string]]::new()
$warnings = [System.Collections.Generic.List[string]]::new()

function Normalize-PathText([string] $path) {
    return $path.Replace("\", "/").Trim("/")
}

function Add-Justifications($set, $entries, [string[]] $propertyNames) {
    foreach ($entry in @($entries)) {
        if ($null -eq $entry) {
            continue
        }

        if ($entry -is [string]) {
            [void] $set.Add((Normalize-PathText $entry))
            continue
        }

        foreach ($propertyName in $propertyNames) {
            $property = $entry.PSObject.Properties[$propertyName]
            if ($null -ne $property -and -not [string]::IsNullOrWhiteSpace($property.Value)) {
                [void] $set.Add((Normalize-PathText ([string] $property.Value)))
                break
            }
        }
    }
}

function Get-RepositoryCSharpFiles {
    $gitFiles = & git -C $root ls-files --cached --others --exclude-standard -- "*.cs"
    if ($LASTEXITCODE -eq 0 -and $null -ne $gitFiles) {
        return @($gitFiles | ForEach-Object { Normalize-PathText $_ })
    }

    return @(Get-ChildItem -LiteralPath $root -Recurse -Filter "*.cs" -File |
        Where-Object {
            $_.FullName -notmatch "\\(bin|obj|\.git)\\"
        } |
        ForEach-Object {
            Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $_.FullName))
        })
}

function Test-GeneratedFile([string] $relativePath) {
    $name = [System.IO.Path]::GetFileName($relativePath)
    if ($name -match "\.(g|generated|designer)\.cs$") {
        return $true
    }

    $fullPath = Join-Path $root $relativePath
    if (-not (Test-Path -LiteralPath $fullPath)) {
        return $true
    }

    $head = Get-Content -LiteralPath $fullPath -TotalCount 20
    return ($head -match "<auto-generated").Count -gt 0
}

function Get-LineCount([string] $relativePath) {
    $count = 0
    foreach ($line in [System.IO.File]::ReadLines((Join-Path $root $relativePath))) {
        $count++
    }

    return $count
}

function Get-Folder([string] $relativePath) {
    $folder = [System.IO.Path]::GetDirectoryName($relativePath)
    if ([string]::IsNullOrWhiteSpace($folder)) {
        return "."
    }

    return Normalize-PathText $folder
}

$justifiedFiles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedRootFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

if (Test-Path -LiteralPath $justificationPath) {
    $justifications = Get-Content -Raw -LiteralPath $justificationPath | ConvertFrom-Json
    Add-Justifications $justifiedFiles $justifications.files @("path", "file")
    Add-Justifications $justifiedFolders $justifications.folders @("path", "folder")
    Add-Justifications $justifiedRootFolders $justifications.rootFolders @("path", "folder", "rootFolder")
}

$csharpFiles = @(Get-RepositoryCSharpFiles | Where-Object { -not (Test-GeneratedFile $_) })
$filesByFolder = @{}
foreach ($file in $csharpFiles) {
    $lineCount = Get-LineCount $file
    $hasJustification = $justifiedFiles.Contains($file)

    if ($lineCount -gt 500 -and -not $hasJustification) {
        $violations.Add("CE0003 $file has $lineCount lines and exceeds 500 lines without a justification.")
    }
    elseif ($lineCount -gt $FailAt -and -not $hasJustification) {
        $violations.Add("CE0001 $file has $lineCount lines, exceeding the hard limit of $FailAt.")
    }
    elseif ($lineCount -gt $WarnAt) {
        $warnings.Add("CE0002 $file has $lineCount lines, exceeding the soft limit of $WarnAt.")
    }

    $folder = Get-Folder $file
    if (-not $filesByFolder.ContainsKey($folder)) {
        $filesByFolder[$folder] = [System.Collections.Generic.List[string]]::new()
    }

    $filesByFolder[$folder].Add($file)
}

foreach ($folder in $filesByFolder.Keys) {
    $count = $filesByFolder[$folder].Count
    if ($count -gt $MaxFilesPerFolder -and -not $justifiedFolders.Contains($folder)) {
        $violations.Add("CE0004 $folder contains $count C# files, exceeding the folder limit of $MaxFilesPerFolder.")
    }
}

$projectFolders = @(Get-ChildItem -LiteralPath $root -Recurse -Filter "*.csproj" -File |
    Where-Object { $_.FullName -notmatch "\\(bin|obj|\.git)\\" } |
    ForEach-Object { Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $_.DirectoryName)) } |
    Select-Object -Unique)

foreach ($projectFolder in $projectFolders) {
    $count = if ($filesByFolder.ContainsKey($projectFolder)) { $filesByFolder[$projectFolder].Count } else { 0 }
    if ($count -gt $MaxFilesInProjectFolder -and -not $justifiedRootFolders.Contains($projectFolder)) {
        $violations.Add("CE0005 $projectFolder contains a .csproj and $count C# files, exceeding the project-folder limit of $MaxFilesInProjectFolder.")
    }
}

foreach ($warning in $warnings) {
    Write-Warning $warning
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        Write-Error $violation -ErrorAction Continue
    }

    throw "CodeEnforcer found $($violations.Count) violation(s)."
}

Write-Host "CodeEnforcer passed."
