namespace SafeIR.PluginAnalyzer;

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

/// <summary>
/// Emits the C# interceptors that replace each lowered chain's <c>InvokeKernel(lambda)</c> call site
/// with <c>HookPipeline.UseGeneratedChain(&lt;ChainPackage&gt;.Create())</c>, plus the
/// <c>InterceptsLocationAttribute</c> definition. Consuming projects opt in by adding the interceptor
/// namespace to <c>&lt;InterceptorsNamespaces&gt;</c> (<c>SafeIR.Plugins.Generated</c>).
/// </summary>
internal static class SafeIrHookChainInterceptorEmitter
{
    public const string InterceptorNamespace = "SafeIR.Plugins.Generated";

    private const string AttributeSource =
        "// <auto-generated/>\n" +
        "namespace System.Runtime.CompilerServices\n" +
        "{\n" +
        "    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]\n" +
        "    internal sealed class InterceptsLocationAttribute : global::System.Attribute\n" +
        "    {\n" +
        "        public InterceptsLocationAttribute(int version, string data) { _ = version; _ = data; }\n" +
        "    }\n" +
        "}\n";

    public static void Emit(SourceProductionContext context, ImmutableArray<HookChainInterception> interceptions)
    {
        if (interceptions.IsDefaultOrEmpty)
        {
            return;
        }

        context.AddSource("SafeIrInterceptsLocationAttribute.g.cs", AttributeSource);
        context.AddSource("SafeIrHookChainInterceptors.g.cs", BuildInterceptors(interceptions));
    }

    private static string BuildInterceptors(ImmutableArray<HookChainInterception> interceptions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").AppendLine(InterceptorNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    internal static class HookChainInterceptors");
        builder.AppendLine("    {");

        for (var i = 0; i < interceptions.Length; i++)
        {
            var interception = interceptions[i];
            var handlerType = interception.HandlerIsAction
                ? $"global::System.Action<{interception.EventTypeFullName}, global::SafeIR.Server.Abstractions.HookContext>"
                : $"global::System.Func<{interception.EventTypeFullName}, global::SafeIR.Server.Abstractions.HookContext, global::System.Threading.Tasks.ValueTask>";

            builder.Append("        ").AppendLine(interception.AttributeSyntax);
            builder.Append("        public static global::SafeIR.Plugins.HookPipeline<")
                .Append(interception.EventTypeFullName)
                .Append("> Intercept_")
                .Append(i.ToString(System.Globalization.CultureInfo.InvariantCulture))
                .AppendLine("(");
            builder.Append("            this global::SafeIR.Plugins.HookPipeline<")
                .Append(interception.EventTypeFullName)
                .AppendLine("> pipeline,");
            builder.Append("            ").Append(handlerType).AppendLine(" handler)");
            builder.Append("            => pipeline.UseGeneratedChain(")
                .Append(interception.PackageFullName)
                .AppendLine(".Create());");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
