namespace AgentQueue;

internal static class AgentQueueDefaults
{
    public const string Readme = """
        # Agent Loop

        This folder contains the multi-agent finding queue.

        Do not manually edit generated queue files.

        Use `agentq`:

        ```bash
        agentq append ...
        agentq claim ...
        agentq fix ...
        agentq verify ...
        agentq render
        agentq doctor
        ```

        Status flow:

        ```text
        open -> claimed -> fixed_pending_verification -> verified
        ```

        Auditors create findings.
        Fixers fix one finding at a time.
        Verifiers close findings.
        """;

    public const string ConfigJson = """
        {
          "version": 1,
          "areas": {
            "completeness": { "prefix": "CMP", "queueFile": "completeness.md" },
            "correctness": { "prefix": "COR", "queueFile": "correctness.md" },
            "perf_alloc": { "prefix": "PAL", "queueFile": "perf-alloc.md" },
            "perf_algorithm": { "prefix": "ALG", "queueFile": "perf-algorithm.md" },
            "api_coherence": { "prefix": "API", "queueFile": "api-coherence.md" },
            "test_coverage": { "prefix": "TST", "queueFile": "test-coverage.md" }
          },
          "priorities": [ "critical", "high", "medium", "low", "idea" ],
          "statuses": [
            "open",
            "claimed",
            "fixed_pending_verification",
            "verified",
            "rejected",
            "duplicate",
            "obsolete"
          ],
          "forbidSelfVerification": true,
          "queueGeneratedWarning": "<!-- GENERATED BY agentq render. DO NOT EDIT BY HAND. Source of truth: docs/agent-loop/findings/*.md -->"
        }
        """;

    public const string CurrentFix = """
        # Current Fix

        Finding:
        Status:
        Fix branch:
        Started from commit:
        Owner:

        ## Goal

        One sentence describing the exact finding being fixed.

        ## Required validation

        - [ ] Relevant unit tests pass.
        - [ ] Regression test added/updated where practical.
        - [ ] Benchmark/allocation test added/updated for perf findings where practical.
        - [ ] `agentq render --check` passes.
        - [ ] `agentq doctor` passes.

        ## Files likely involved

        - `src/...`
        - `tests/...`

        ## Notes

        Add active notes here. This file is coordination state, not source of truth.
        """;
}
